name: openaccounting
description: "📊 Open-Source & Privacy-Friendly Desktop App for your Accounting, Invoices and Tax Reports. Designed for Freelancers."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.31.1
  mockito: ^5.8.1
  build_runner: ^2.16.0

flutter:
  uses-material-design: true
  generate: true